# folders and paths
data_folder: "data/data_PRMstar"
nn_folder: "models/data_PRMstar"
prm_folder: "prm"

# Environment
bounds: [-2.0, 2.0, -2.0, 2.0]

obstacles:
      box1:
        - -0.5
        - -0.5
        - 0.6
      box2:
        - -1.2
        - 1.2
        - 0.3
      box3:
        - 0.8
        - 1.0
        - 0.3
      box4:
        - 0.4
        - -1.1
        - 0.3
      box5:
        - 0.9
        - 0.1
        - 0.3
      box6:
        - -1.5
        - -1.0
        - 0.2
      box7:
        - 1.2
        - -0.6
        - 0.2
      box8:
        - -0.9
        - 0.3
        - 0.15
      box9:
        - 0.0
        - 0.8
        - 0.15

# PRM
nodes: 2000
num_samples: 100000
version: 1

# Neural Network
learning_rate: 100 # will be used as 1/lr in the code
epochs: 200
nn_version: 1

# MPC
horizon_length: 15
terminal_cost_type: "nn" # "nn" or "heuristic"
start: [0.0, 0.0]
goal: [1.5, 1.0]
Q: [0.01, 0.001]
R: [0.001, 0.001]
W: 0.001