# folders and paths
data_folder: "data/data_PRMstar"
nn_folder: "models/data_PRMstar"
prm_folder: "prm"

# Environment
bounds: [-2.0, 2.0, -2.0, 2.0]

obstacles:
      box1:
        - -0.5
        - -0.5
        - 0.6
      box2:
        - -1.2
        - 1.2
        - 0.3
      box3:
        - 0.8
        - 1.0
        - 0.3
      box4:
        - 0.4
        - -1.1
        - 0.3
      box5:
        - 0.9
        - 0.1
        - 0.3
      box6:
        - -1.5
        - -1.0
        - 0.2
      box7:
        - 1.2
        - -0.6
        - 0.2
      box8:
        - -0.9
        - 0.3
        - 0.15
      box9:
        - 0.0
        - 0.8
        - 0.15

# PRM
nodes: 2000
num_samples: 100000
version: 1

# Neural Network
learning_rate: 1000 # will be used as 1/lr in the code
epochs: 100
optimizer: "AdamW" # "SGD", "Adam", or "AdamW"
dropout_rate: 0.0 # only used for nn_version 3
weight_decay: 100 # only used for AdamW optimizer
nn_version: 3

# MPC
horizon_length: 8
terminal_cost_type: "heuristic" # "nn" or "heuristic"
start: [0.0, 0.0]
goal: [-1.0, -1.5]
Q: [0.1, 0.01]  # weight for [dx, dy], dtheta (useing the same Q for dx and dy)
R: [0.001, 0.001] # weight for v, omega  
W: 0.0001          # weight for obstacle cost
T: 1.0            # weight for terminal cost