#############################################################
# Config file for PRM, Neural Network, and MPC
#############################################################

# folders and paths
data_folder: "data/data_PRMstar"
nn_folder: "models/data_PRMstar"
prm_folder: "prm/world2"
world: "world2"
data_mpc_path: "data/mpc_path"

# Environment
# Obstacle Format: [x, y, half_width_x, half_length_y]
world1:
  bounds: [-2.0, 2.0, -2.0, 2.0]
  obstacles: [
    [-0.5, -0.5, 0.3, 0.3],
    [-1.2, 1.2, 0.15, 0.15],
    [0.8, 1.0, 0.15, 0.15],
    [0.4, -1.1, 0.15, 0.15],
    [0.9, 0.1, 0.15, 0.15],
    [-1.5, -1.0, 0.1, 0.1],
    [1.2, -0.6, 0.1, 0.1],
    [-0.9, 0.3, 0.075, 0.075],
    [0.0, 0.8, 0.075, 0.075]
    ]

world2:
  bounds: [-2.0, 2.0, -2.5, 2.0]
  obstacles: [
    # Horizontal Walls
    [-0.5, 1.4, 0.5, 0.05],
    [-0.7, 0.6, 0.7, 0.05],
    [-0.7, -0.6, 0.7, 0.05],
    [-0.8, -1.8, 0.6, 0.05],
    [0.55, -0.2, 0.55, 0.05],
    [0.35, -1.2, 0.35, 0.05],
    [0.9, 1.0, 0.2, 0.05],
    
    # Vertical Walls
    [0.0, 0.4, 0.05, 1.0],    
    [-1.0, 0.6, 0.05, 0.4],   
    [-0.7, -1.2, 0.05, 0.6],  
    [1.1, 0.4, 0.05, 0.6],    
    [0.7, -1.0, 0.05, 0.8]    
  ]

# PRM
nodes: 2000
num_samples: 100000
version: 1
selected_prm: "prm_1528.pkl"

# Neural Network 
# (BEST average abs error: nn_dr0_AdamW100_epochs100_lr1000_dataset100000_1.pth (nn_version 3))
# (BEST max error: nn8_dr0_AdamW10_epochs150_lr1000_dataset100000_1.pth (nn_version 3))
learning_rate: 1000 # will be used as 1/lr in the code
epochs: 200
optimizer: "AdamW" # "SGD", "Adam", or "AdamW"
dropout_rate: 0.0  # only used for nn_version 3
weight_decay: 100  # only used for AdamW optimizer
nn_version: 9      # version of nn to choose

# MPC```cond
case: 3
# start: [-1.7, -0.1, 270]   # 1
# start: [1.95, 1.95, 180] # 2 
start: [-0.3, 1.0, 0]  # 3
goal: [-1.2, -1.3]
horizon_length: 12
terminal_cost_type: "nn"  # "nn" or "heurstic"
Q: [0.5, 0.01]     # weight for [dx, dy], dtheta (useing the same Q for dx and dy)
R: [0.01, 0.01]   # weight for v, omega  
W: 50.0           # weight for obstacle cost
T: 30.0           # weight for terminal cost